##################################################################################
# This agent selects actions randomly. (Useful for debugging purposes.)
##################################################################################

agent_type: 'random'

device: {device}
seed: ${seed}
normalize_observation: False